### PR TITLE
Add investment tax credit

### PR DESCRIPTION
**Pull request by jdebacker**
This PR adds an investment tax credit parameter to the model.

### CODE REVIEW

**Comment by jdebacker** [comment]
This PR is ready for review @rickecon

**Comment by rickecon** [comment]
@jdebacker.
* I just submitted a PR to your branch, which PR updates the documentation to reflect the investment tax credit.
* I made a comment above that I think you need to add `tau_inv` to the new `get_K_from_Y()` function in `firm.py`.
* I think you are missing the `tau_inv` argument in the `revenue()` function in `aggregates.py`.
* In going through the theory, I found that the profit function, `r_t` FOC condition on capital, revenue function, capital-output ratio, and `K^{r^*}_{m,t}` all had the new `tau_inv` argument. You should probably do one more time through to make sure you caught all of them.
* These changes might require updating the new tests.

**Comment by jdebacker** [comment]
@rickecon - Thank for the review.  Let me respond to your comments:

> I just submitted https://github.com/jdebacker/OG-Core/pull/27 to your branch, which PR updates the documentation to reflect the investment tax credit.

This is great - thank you!

> I made a comment above that I think you need to add tau_inv to the new get_K_from_Y() function in firm.py.

This function is deprecated.  Its only use is to get some values for `r_p` in `test_SS.py` in order to be able to use cached values from before the refactoring in PR #791 for the tests of `SS.inner_loop`.  Let me go ahead and update the cached values for those tests and I can remove this function from `firm.py`.

> I think you are missing the tau_inv argument in the revenue() function in aggregates.py.

`aggregates.revenue()` calls `tax.get_biz_tax()`, which does account for the revenue costs of the investment tax credit. Updated tests of this function use a non-zero value for the investment tax credit to confirm the logic.

> In going through the theory, I found that the profit function, r_t FOC condition on capital, revenue function, capital-output ratio, and K^{r^*}_{m,t} all had the new tau_inv argument. You should probably do one more time through to make sure you caught all of them.

I confirm all these functions account for the investment tax credit. A few of them call the `firm.get_cost_of_capital()` function, where the investment tax credit is included (e.g. the KY ratio, and K^{r*)_{m,t}

**Comment by rickecon** [comment]
@jdebacker said regarding my comment about the `get_K_from_Y()` function in `firm.py`:

> ...Let me go ahead and update the cached values for those tests and I can remove this function from `firm.py`.

Let me know when this is done.

**Comment by rickecon** [comment]
@jdebacker . The first test in `test_SS.py` failed the first time it ran in the `build (3.10)` CI tests. I just re-ran the tests and they passed. That is pretty weird.

I am ready to merge this as soon as you give me the green light on the comment above.

**Comment by jdebacker** [comment]
@rickecon I've addressed the comment above, removing `firm.get_K_from_Y`.

Included also was the addition of a parameter the let's one choose whether or not to use the baseline solution as the initial guess for the reform (Issue #811) and a simplification of the formula for `tax.MTR_wealth`.

**Comment by rickecon** [comment]
@jdebacker. It looks like you just need to run `black` on `ogcore/tax.py`. Then this is ready to go.

**Comment by jdebacker** [comment]
Ok - just updated the formatting.

**Pull request merged**
