### PR TITLE
Remove mkl dependency from environment.yml and setup.py

### PR DESCRIPTION
**Pull request by rickecon**
@jdebacker. This PR removes the `mkl` Intel processor numerical computation accelerator package dependency from `environment.yml` and `setup.py`. @SeaCelo noted in Issue #821 that the `mkl` dependency is incompatible with Apple M1 processor machines that use the M1 optimized Python distribution from Anaconda. I ran some speed tests (reported [here](https://github.com/PSLmodels/OG-Core/issues/821#issuecomment-1349498207)) on Linux and the two relevant specifications of Mac OSx to see if removing the `mkl` package caused any big slowdowns in computation time, which it does not.

If all our CI tests pass, and the full set of tests pass on my machine, then I propose we merge this update. This will make loading the OG-Core environment and any of the country-specific calibrations compatible with all current Windows, Linux, and Mac operating system and anaconda configurations.

### CODE REVIEW

**Comment by rickecon** [comment]
@jdebacker. I removed the `conda.recipe/` folder from the repo because I don't think we use it since we committed to PyPI.org.

**Comment by rickecon** [comment]
@jdebacker. This passed all tests locally on my machine.
```
============================= test session starts ==============================
platform darwin -- Python 3.10.8, pytest-7.2.0, pluggy-1.0.0
rootdir: /Users/richardevans/Docs/Economics/OSE/OG-Core, configfile: pytest.ini, testpaths: ./tests
plugins: xdist-3.1.0
collected 489 items                                                            

tests/test_SS.py .............................                           [  5%]
tests/test_TPI.py ...........................                            [ 11%]
tests/test_aggregates.py .....................................           [ 19%]
tests/test_basic.py ....                                                 [ 19%]
tests/test_elliptical_u_est.py .......                                   [ 21%]
tests/test_execute.py .                                                  [ 21%]
tests/test_firm.py ..................................................... [ 32%]
.............                                                            [ 34%]
tests/test_fiscal.py ..................                                  [ 38%]
tests/test_household.py ..............................................   [ 48%]
tests/test_output_plots.py ............................................. [ 57%]
                                                                         [ 57%]
tests/test_output_tables.py .............                                [ 59%]
tests/test_parameter_plots.py ...................................        [ 67%]
tests/test_parameter_tables.py .......                                   [ 68%]
tests/test_parameters.py .............                                   [ 71%]
tests/test_run_example.py ..                                             [ 71%]
tests/test_run_ogcore.py .                                               [ 71%]
tests/test_tax.py ......................................                 [ 79%]
tests/test_txfunc.py ..........................                          [ 84%]
tests/test_user_inputs.py .........                                      [ 86%]
tests/test_utils.py .................................................... [ 97%]
.............                                                            [100%]
=========== 0 failed, 489 passed, 77 warnings in 13863.08s (3:51:03) ===========
```

**Comment by jdebacker** [comment]
LGTM and local tests passing on my machine as well.  Thanks @rickecon.

**Comment by SeaCelo** [comment]
@rickecon, @jdebacker:   FYI I cannot run the model if I use this version of the `environment.yml` to build the conda environment. The model complains about missing `pip`, `pandas-datareader`, `ogcore`, `statsmodels`. Adding these lines back solves the problem.

I tested by using this version of `environment.yml` to install the OG-ZAF model:
1. `conda env remove --name ogzaf-dev`
2. `conda env create -f environment.yml`
3. `conda activate ogzaf-dev`
4. `pip install -e .`
5. `python run_og_zaf.py`

**Comment by rickecon** [comment]
@SeaCelo. I will look into this. I think it is because we have not yet uploaded the new package to PyPI.org, and both environment files in OG-ZAF download the version of OG-Core from PyPI.org. The current version on PyPI is 0.10.0, and it needs to be 0.10.1. @jdebacker and I will get this updated this weekend. Thanks for the reminder.

**Comment by rickecon** [comment]
@SeaCelo. I submitted [a PR](https://github.com/EAPD-DRB/OG-ZAF/pull/25) to OG-ZAF that updates that repository to use this updated version of OG-Core with no `mkl` dependency. Everything works well on my machine, which is an Apple M1 chip, and all tests are passing.

**Pull request merged**
