### PR TITLE
Update language in government.md about closure rule availability

### PR DESCRIPTION
**Pull request by rickecon**
This PR updates the `OG-Core` documentation on government closure rules to specify that only one of the three methods described is currently an option in the model. This PR addresses Issue #783.

cc: @jdebacker

### CODE REVIEW

**Comment by rickecon** [comment]
@jdebacker. Any idea what this error is in the CI on this pull request, which only changes one line in the documentation?
```
E   ImportError: cannot import name 'scope2index' from '_pytest.fixtures' (/usr/share/miniconda/envs/ogcore-dev/lib/python3.8/site-packages/_pytest/fixtures.py)
```

**Comment by rickecon** [comment]
My most recent commit removes the import of the `_pytest.fixtures.scope2index` function. This function was the cause of the failing CI tests. And the import was only in `test_SS.py` and it was not used in those tests. I ran all the `test_SS.py` tests locally with the change and they all passed.
```
ogcore/tests/test_SS.py ................................                 [100%]

```

**Comment by rickecon** [comment]
OK. Now I have three failing tests that are the same as the tests that are failing in PR #785. I'll work on this.

**Comment by rickecon** [comment]
@jdebacker. This very simple PR is now ready for your review.

**Comment by jdebacker** [comment]
Thanks for clearing up the documentation @rickecon!

**Pull request merged**
