### PR TITLE
Standardize time path output

### PR DESCRIPTION
**Pull request by jdebacker**
This PR standardizes the variables saved to the output dictionary from the time path solution.  Previously, some variables had a dimension with length `T+S` while others had a length of `T` in the same dimension (as noted in Issue #879).  This PR sets the first dimension of all time path output variables to be of length `T`.  This consistency in the length along this dimension will help users more easily use the model output.

### CODE REVIEW

**Comment by jdebacker** [comment]
This PR is ready to go.  I ran the full suite of tests locally and found 3 failures:

```
=========================== short test summary info ============================
FAILED tests/test_txfunc.py::test_txfunc_est[DEP] - assert False
FAILED tests/test_txfunc.py::test_tax_func_loop - assert False
FAILED tests/test_txfunc.py::test_monotone_spline - AttributeError: module 'numpy' has no attribute 'int'.
```

The first two are expected to fail since I'm using a different version of SciPy than was used for the cached tax function estimates are checking against (and we know different versions produce slightly different parameter estimates).  The third failure is because the PyGAM package is incompatible with more recent NumPy versions.  If that project would merge [PR #321](https://github.com/dswah/pyGAM/pull/321) (which changes just two lines), this test would pass.

**Review by rickecon — APPROVED** [review]

**Comment by rickecon** [comment]
@jdebacker. This looks great. Will you please update the version number to 0.10.8 in `setup.py` and in `ogcore/__init__.py`. As soon as this is done, I will merge.

**Comment by rickecon** [comment]
@jdebacker. BTW, I keep looking for alternatives to [`PyGAM`](https://github.com/dswah/pyGAM) for generalized additive models. It is not clear to me if there is a good alternative in `scikit-learn`. This Jupyter Book "[Generalized Additive Models (GAM)](https://kirenz.github.io/regression/docs/gam.html)" chapter uses the `gam` module of the `statsmodels` package ([`statsmodels.gam`](https://www.statsmodels.org/devel/gam.html)), which might be an alternative.

**Comment by jdebacker** [comment]
@rickecon Version bump done.  Will look into the alternative to PyGAM - thanks.

**Review by rickecon — APPROVED** [review]

**Pull request merged**
