### PR TITLE
Updates to `txfunc.py`

### PR DESCRIPTION
**Pull request by jdebacker**
This PR will make the following changes:

1. Add another form for individual income tax functions from [Heathcote, Storesletten, and Violante (*QJE*, 2017)](https://academic.oup.com/qje/article-abstract/132/4/1693/3884644).  It's helpful to add these because they are simple to estimate (one can use OLS), allow for progressive taxes, and are widely used in the macroeconomics literature.
2. Improve the choice of starting values when minimizing tax functions via weighted, non-linear least squares.

### CODE REVIEW

**Comment by jdebacker** [comment]
# HSV function estimates (age specific, each line representing a different age)

## ETRs
HSV_PUF_etr

## MTR, labor income
HSV_PUF_mtrx

## MTR, capital income
HSV_PUF_mtry

**Comment by jdebacker** [comment]
@rickecon This PR is ready for your review.

The changes to starting values (which apply to the GS and DEP functions only)  are to estimate the specified tax functions for all ages via a global optimizer (in this case, `scipy.optimize.differential_evolution`), then use these parameter estimates for the initial guess for the first age group. Following that, the parameter estimates for each age are used as starting values for the next age.

**Review by rickecon — APPROVED** [review]

**Comment by rickecon** [comment]
@jdebacker. The Linux/Python 3.10 test seems to be stalled out. I wonder what is going on with the tests. I am just waiting for these all to pass. I approved all the code changes.

**Comment by rickecon** [comment]
@jdebacker. This looks great and all checks have passed. Merging.

**Pull request merged**
