### PR TITLE
Updates to `demographics.py` for changes in UN API

### PR DESCRIPTION
**Pull request by jdebacker**
This PR updates the `demographics.py` module for updates in the UN WPP data portal API, which now requires users to authenticate with an API token.

The PR:
1) Changes the calls to the API to download multiple years at a time, which significantly reduces the number of API calls (Issue #935)
2) Has `demographics.py` look for a file named `un_api_token.txt` in the current directory, and if not there, prompts the user to enter their API token in the command line (Issue #931).
3) Add functionality to read in cached files, pulling the years of data one wants from them. [NOT YET STARTED]

### CODE REVIEW

**Comment by jdebacker** [comment]
To be resolved:
- [ ] Does the prompt for a token work from a Jupyter Notebook?
- [ ] Does the prompt for a token work when running unit tests locally?
- [ ] Is there a way Github Actions can supply the token as a GH secret when running unit tests on GH Actions?
- [ ] What is the best way to allow users to separate run functions (e.g., `get_fert` or `get_mort`) and supply their token to the API?  Current changes are to just ask for it when one pings `get_pop_obj` and that call requires fetching data from the UN.

**Comment by jdebacker** [comment]
One idea: include:

```python
global UN_TOKEN
        # Check for a file named "un_api_token.txt" in the current directory
        if os.path.exists(os.path.join("un_api_token.txt")):
            with open(os.path.join("un_api_token.txt"), "r") as file:
                UN_TOKEN = file.read().strip()
        else:  # if file not exist, prompt user for token
            UN_TOKEN = input("Please enter your UN API token: ")
```

in `get_un_data`, but have a command following the user input prompt to save the token to a file named `un_api_token.txt`.  This way, on subsequent calls to the API, the token is just read from a file.

Would there be any security concerns with this?  e.g., a user's token saved on a device that isn't theirs?   

To solve that, we can have a separate prompt, for "save token to disk" and only write to disk if yes...

**Comment by jdebacker** [comment]
This PR now handles UN data access in the following way:
* User is prompted to enter token, any token entered is saved to a file, `un_api_token.txt` for future use.
* If working token is entered, data is fetched from UN WPP data API
* If token entered is incorrect, or if any other issue connecting to UN WPP data API, data is downloaded from the [EAPD Population-Data repo.](https://github.com/EAPD-DRB/Population-Data).

@rickecon @SeaCelo, let me know if the changes in `demographics.py` look good to you.

**Comment by SeaCelo** [comment]
@jdebacker This is a sensible approach. I'll test it and see if there are any issues

**Comment by rickecon** [comment]
@jdebacker. This looks great. Merging as soon as tests pass. I just committed one extra change at the end of `CHANGELOG.md` that adds the hyperlink.

**Review by rickecon — APPROVED** [review]

**Pull request merged**
