### PR TITLE
Relax dependencies

### PR DESCRIPTION
**Pull request by jdebacker**
This PR removes the hard pins in the package dependencies of OG-Core.  The hope is to reduce conflicts when installing in other environments and with other packages.

### CODE REVIEW

**Comment by jdebacker** [comment]
In local testing, I am finding errors when trying to read in the pickle file used for the `tests/test_txfunc.py::test_txfunc_est` tests.  And example traceback is:

```
____________________________________________ test_txfunc_est_on_GH[linear, mtry] ____________________________________________

file_path = '/Users/jason.debacker/repos/dynamic/ogcore/tests/test_io_data/txfunc_est_inputs.pkl'

    def safe_read_pickle(file_path):
        '''
        This function reads a pickle from Python 2 into Python 2 or Python 3

        Args:
            file_path (str): path to pickle file

        Returns:
            obj (object): object saved in pickle file

        '''
        with open(file_path, 'rb') as f:
            try:
>               obj = pickle.load(f, encoding='latin1')

utils.py:359:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cls = <class 'pandas.core.internals.managers.BlockManager'>, base = <class 'object'>, state = None

    def _reconstructor(cls, base, state):
        if base is object:
>           obj = object.__new__(cls)
E           TypeError: object.__new__(BlockManager) is not safe, use BlockManager.__new__()

../../../anaconda3/envs/ogcore-dev/lib/python3.9/copyreg.py:43: TypeError

During handling of the above exception, another exception occurred:

rate_type = 'mtry', tax_func_type = 'linear', numparams = 1, expected_tuple = (0.15604427, 0.0, 3798)
tmpdir = local('/private/var/folders/b0/wwxd0byd1hx0y_rqrnqhmc0m0000gn/T/pytest-of-jason.debacker/pytest-4/test_txfunc_est_on_GH_linear__1')

    @pytest.mark.parametrize('rate_type,tax_func_type,numparams,expected_tuple',
                             [('etr', 'linear', 1, expected_tuple_linear),
                              ('etr', 'GS', 3, expected_tuple_GS),
                              ('mtrx', 'linear', 1,
                               expected_tuple_linear_mtrx),
                              ('mtry', 'linear', 1,
                               expected_tuple_linear_mtry)],
                             ids=['linear', 'GS', 'linear, mtrx',
                                  'linear, mtry'])
    def test_txfunc_est_on_GH(rate_type, tax_func_type, numparams,
                              expected_tuple, tmpdir):
        '''
        Test txfunc.txfunc_est() function.  The test is that given
        inputs from previous run, the outputs are unchanged.
        '''
>       input_tuple = utils.safe_read_pickle(
            os.path.join(CUR_PATH, 'test_io_data', 'txfunc_est_inputs.pkl'))

tests/test_txfunc.py:209:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
utils.py:361: in safe_read_pickle
    obj = pickle.load(f)  # pragma no cover
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cls = <class 'pandas.core.internals.managers.BlockManager'>, base = <class 'object'>, state = None

    def _reconstructor(cls, base, state):
        if base is object:
>           obj = object.__new__(cls)
E           TypeError: object.__new__(BlockManager) is not safe, use BlockManager.__new__()

../../../anaconda3/envs/ogcore-dev/lib/python3.9/copyreg.py:43: TypeError
```

**Comment by rickecon** [comment]
@jdebacker. I am worried that this is the wrong solution. We should try not to move backward in terms of package versions. I think we should encourage work on the `openfisca`, `microdf`, and `synthimpute` packages to move forward in terms of compatibility.

**Comment by jdebacker** [comment]
@rickecon comments:

> I am worried that this is the wrong solution. We should try not to move backward in terms of package versions.

This doesn't move anything backwards.  Rather it removed hard pins and replaces them with ">=".  So versions will be *at least as new* as what they would be before this PR.

**Comment by jdebacker** [comment]
@rickecon this PR is ready for your review. Thanks!

**Comment by rickecon** [comment]
This looks good to me. Merging.

**Pull request merged**
