### PR TITLE
Update build_and_test.yml GitHub Action

### PR DESCRIPTION
**Pull request by rickecon**
This PR updates the `build_and_test.yml` in the following ways:
* Adds three operating systems, including `Mac OS` to `build_and_test.yml`
* Removes the Python 3.8 tests, so this only tests Python 3.9 and 3.10
* Updates to `actions/checkout@v3`
* Updates to `codecov/codecov-action@v3`
* Remove unused `from curses.ascii import SP` from `test_firms.py`. This unused import was causing the tests to fail on Windows latest platform with Python 3.9.
* Update and add badges to the `README.md`
* Updated expected values and tolerance level in `test_SS_fsolve()` test and updated tolerance level in `test_run_SS()` test in `test_SS.py`
* Added tolerance level to `test_twist_doughnut()` in test_TPI.py`

### CODE REVIEW

**Comment by rickecon** [comment]
@jdebacker. Whoa! This worked. All tests on Python 3.9 and 3.10 passed on all three operating systems. I suggest we incorporate this into the repo. I did relax one of the `np.allclose()` tolerances to 1e-05 in `test_TPI.py`. And I need to restore the first test in `test_SS.py`. I will restore that `test_SS.py` first test `test_SS_fsolve()`, and it will fail. But I think we should update the stored values so it passes.

**Comment by rickecon** [comment]
@jdebacker. Even though all the CI tests are passing, I have a bunch of marked local test that are not passing on my machine (see output below). Three of these are `test_txfunc.py` `np.allclose()` discrepancies, which I can fix by updating the expected values. This should be OK for these local tests. Then the other four (3 in `test_SS.py` and one in `test_run_example.py`) are runtime errors where the steady state is not found. These four will be fixed by resolving Issue #831. So I am going to fix the three `test_txfunc.py` failures in this PR. And I might just go ahead and resolve Issue #831 here as well. I'll let you know if I leave that last one for another PR.
```
========================= test session starts =======================================
platform darwin -- Python 3.10.8, pytest-7.2.0, pluggy-1.0.0
rootdir: /Users/richardevans/Docs/Economics/OSE/OG-Core, configfile: pytest.ini, testpaths: ./tests
plugins: xdist-3.1.0
collecting 93 items                                                                    collected 489 items                                                                   

tests/test_SS.py ...................FF..F.....                                  [  5%]
tests/test_TPI.py ...........................                                   [ 11%]
tests/test_aggregates.py .....................................                  [ 19%]
tests/test_basic.py ....                                                        [ 19%]
tests/test_elliptical_u_est.py .......                                          [ 21%]
tests/test_execute.py .                                                         [ 21%]
tests/test_firm.py .................................................................. [ 34%]
tests/test_fiscal.py ..................                                         [ 38%]
tests/test_household.py ..............................................          [ 48%]
tests/test_output_plots.py .............................................        [ 57%]
tests/test_output_tables.py .............                                       [ 59%]
tests/test_parameter_plots.py ...................................               [ 67%]
tests/test_parameter_tables.py .......                                          [ 68%]
tests/test_parameters.py .............                                          [ 71%]
tests/test_run_example.py F.                                                    [ 71%]
tests/test_run_ogcore.py .                                                      [ 71%]
tests/test_tax.py ......................................                        [ 79%]
tests/test_txfunc.py .....F.......F..........F.                                 [ 84%]
tests/test_user_inputs.py .........                                             [ 86%]
tests/test_utils.py ................................................................. [100%]
=============================== short test summary info ===============================
FAILED tests/test_SS.py::test_run_SS[Baseline, use zeta] - RuntimeError: Steady state equilibrium not found
FAILED tests/test_SS.py::test_run_SS[Reform, baseline spending, use zeta] - RuntimeError: Steady state equilibrium not found
FAILED tests/test_SS.py::test_run_SS[Reform, use zeta] - RuntimeError: Steady state equilibrium not found
FAILED tests/test_run_example.py::test_run_ogcore_example - assert False
FAILED tests/test_txfunc.py::test_txfunc_est[DEP] - assert False
FAILED tests/test_txfunc.py::test_tax_func_loop - assert False
FAILED tests/test_txfunc.py::test_tax_func_estimate - assert False
```

**Comment by rickecon** [comment]
@jdebacker. My updates to `SS.py` have solved the local failures in `test_SS.py` and `test_run_example.py`. Merging this PR resolves Issue #831.
```
tests/test_SS.py .............................                           [100%]
tests/test_run_example.py ..                                             [100%]
```
Now I am working on the `test_txfunc.py` tests.

**Comment by rickecon** [comment]
@jdebacker. The last four commits fix all the tests that were not passing locally on my machine in `test_txfunc.py`.
```
tests/test_txfunc.py ..........................      [100%]

```
All tests now pass locally. This PR is ready for review and merge.

**Comment by rickecon** [comment]
@jdebacker. I think the updates in this PR will resolve the CI test that is failing in @prrathi's PR #839.

**Comment by rickecon** [comment]
@jdebacker. All tests passing locally. This PR is ready to go.
```
========================================== test session starts ===========================================
platform darwin -- Python 3.10.8, pytest-7.2.0, pluggy-1.0.0
rootdir: /Users/richardevans/Docs/Economics/OSE/OG-Core, configfile: pytest.ini, testpaths: ./tests
plugins: xdist-3.1.0
collected 489 items                                                                                      

tests/test_SS.py .............................                                                     [  5%]
tests/test_TPI.py ...........................                                                      [ 11%]
tests/test_aggregates.py .....................................                                     [ 19%]
tests/test_basic.py ....                                                                           [ 19%]
tests/test_elliptical_u_est.py .......                                                             [ 21%]
tests/test_execute.py .                                                                            [ 21%]
tests/test_firm.py ..................................................................              [ 34%]
tests/test_fiscal.py ..................                                                            [ 38%]
tests/test_household.py ..............................................                             [ 48%]
tests/test_output_plots.py .............................................                           [ 57%]
tests/test_output_tables.py .............                                                          [ 59%]
tests/test_parameter_plots.py ...................................                                  [ 67%]
tests/test_parameter_tables.py .......                                                             [ 68%]
tests/test_parameters.py .............                                                             [ 71%]
tests/test_run_example.py ..                                                                       [ 71%]
tests/test_run_ogcore.py .                                                                         [ 71%]
tests/test_tax.py ......................................                                           [ 79%]
tests/test_txfunc.py ..........................                                                    [ 84%]
tests/test_user_inputs.py .........                                                                [ 86%]
tests/test_utils.py .................................................................              [100%]

```

**Comment by jdebacker** [comment]
I found four test failures:

```
============================= test session starts ==============================
platform darwin -- Python 3.10.8, pytest-7.2.0, pluggy-1.0.0
rootdir: /Users/jason.debacker/repos/OG-Core, configfile: pytest.ini, testpaths: ./tests
plugins: xdist-3.1.0
collected 489 items

tests/test_SS.py .............................                           [  5%]
tests/test_TPI.py ...........................                            [ 11%]
tests/test_aggregates.py .....................................           [ 19%]
tests/test_basic.py ....                                                 [ 19%]
tests/test_elliptical_u_est.py .......                                   [ 21%]
tests/test_execute.py .                                                  [ 21%]
tests/test_firm.py ..................................................... [ 32%]
.............                                                            [ 34%]
tests/test_fiscal.py ..................                                  [ 38%]
tests/test_household.py ..............................................   [ 48%]
tests/test_output_plots.py ............................................. [ 57%]
                                                                         [ 57%]
tests/test_output_tables.py .............                                [ 59%]
tests/test_parameter_plots.py ...................................        [ 67%]
tests/test_parameter_tables.py .......                                   [ 68%]
tests/test_parameters.py .............                                   [ 71%]
tests/test_run_example.py ..                                             [ 71%]
tests/test_run_ogcore.py .                                               [ 71%]
tests/test_tax.py ......................................                 [ 79%]
tests/test_txfunc.py .....F.F.....F..........F.                          [ 84%]
tests/test_user_inputs.py .........                                      [ 86%]
tests/test_utils.py .................................................... [ 97%]
.............                                                            [100%]
=========================== short test summary info ============================
FAILED tests/test_txfunc.py::test_txfunc_est[DEP] - assert False
FAILED tests/test_txfunc.py::test_txfunc_est[GS] - assert False
FAILED tests/test_txfunc.py::test_tax_func_loop - assert False
FAILED tests/test_txfunc.py::test_tax_func_estimate - assert False
========== 4 failed, 485 passed, 78 warnings in 43642.11s (12:07:22) ===========
```

**Comment by rickecon** [comment]
@jdebacker. All the test failures are in `test_txfunc.py`. Those `np.allclose()` asserts have big values in them, including sum of squared errors in units of 100,000 and 1,000,000. We get deviations across platforms that break these tests. The only solution is to adjust tolerances, and probably to use the `rtol` argument (see [np.allclose documentation](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html)). Do you want to do this? Or another solution is for me to restore the .pkl files I changed and get my tests to pass using the `rtol` argument. Do you want me to do that?

**Comment by jdebacker** [comment]
> Or another solution is for me to restore the .pkl files I changed and get my tests to pass using the rtol argument. Do you want me to do that?

If you do this, will the tests pass on all platforms? Or is the only way to get the tests to pass on all platforms to adjust the `rtol` argument?

**Comment by rickecon** [comment]
@jdebacker. I don't know if I can get the tests to pass on all platforms with an acceptably low tolerance (either `atol` or `rtol`). But I could try.

But here is something to consider. It took you 12 hours to run the full set of tests on your machine. It takes me less than four hours. We need to use the M1 chip platform and the Anaconda architecture designed for it. Most of the time it will only be you and I running the full set of tests. If it is difficult to get those `test_txfunc.py` tests to pass across platforms, it might be worth just making sure those tests pass on our machines. Otherwise, we need to rewrite the tests themselves.

**Comment by jdebacker** [comment]
In looking at the test failures again, I don't think this is a case where adjusting tolerances would be helpful.  Take, for example, `test_txfunc_est[GS]`.  In this case, the test results array (on my machine with Python 3.10.8) is:
```
array([0.42897179, 0.39679734, 0.00239574])
```
And the expected array is:
```
array([3.03099171e-01, 9.64733478e-01, 1.77900933e-05])
```

These are just substantially different coefficient estimates. 

Now, this has nothing to do with this PR -- these test failures would have come from the master branch when run on the latest python and package dependencies.  But before merging, this let me let this sit for a couple of days to see if there's a good work around for this. Perhaps it's just to update the expected results.  But it would be nice to be able to condition results on versions of Python/scipy so that any user can successfully run the local tests.

**Comment by rickecon** [comment]
@jdebacker. I agree. These tests in `test_txfunc.py` are problematic. I think we do need to rewrite them with a different metric of closeness. But also, I think we are moving more toward these nonparametric tax function estimates. I think the monotone tax function already strictly dominates any of our parametric univariate tax functions. And I suspect the new PR #839 with 2D monotonic tax functions will dominate the DEP tax functions. So it might not make a lot of sense to spend a lot of time here. These parametric tax functions will likely be relegated to historical holdovers.

**Comment by jdebacker** [comment]
Thanks for this PR, @rickecon! Merging now.

**Pull request merged**
