### PR TITLE
Multiple Industries

### PR DESCRIPTION
**Pull request by jdebacker**
This PR adds multiple production industries to the model.

### CODE REVIEW

**Comment by jdebacker** [comment]
@rickecon There's a lot here, but this is ready for you to take a look.

Please don't merge until I check off the following:
- [ ] Finish update to TPI sol'n algorithm in the documentation
- [ ] Review that all docstrings have been updated appropriately
- [ ] Confirm that the full test suite runs on my machine

Thanks!

**Comment by rickecon** [comment]
@jdebacker. I don't see any test failures on the Python 3.8 build CI tests. I am currently running the full battery of tests locally on my machine. But I am excited to get this one through.

**Comment by rickecon** [comment]
@jdebacker. I ran the full set of tests locally and got the following three failures.
```
=========================== short test summary info ============================
FAILED tests/test_SS.py::test_run_SS[Baseline, use zeta] - RuntimeError: Stea...
FAILED tests/test_TPI.py::test_run_TPI_extra[Baseline, Kg>0] - assert False
FAILED tests/test_run_example.py::test_run_ogcore_example_output - UnicodeDec...
========== 3 failed, 473 passed, 83 warnings in 39905.62s (11:05:05) ===========

============================= test session starts ==============================
platform darwin -- Python 3.10.5, pytest-7.1.2, pluggy-1.0.0
rootdir: /Users/richardevans/Documents/Economics/OSE/OG-Core, configfile: pytest.ini, testpaths: ./tests
plugins: xdist-2.5.0, forked-1.4.0
collected 476 items                                                            

tests/test_SS.py ..................F.........                            [  5%]
tests/test_TPI.py .........................F                             [ 11%]
tests/test_aggregates.py .....................................           [ 19%]
tests/test_basic.py ....                                                 [ 19%]
tests/test_elliptical_u_est.py .......                                   [ 21%]
tests/test_execute.py .                                                  [ 21%]
tests/test_firm.py ..................................................... [ 32%]
.............                                                            [ 35%]
tests/test_fiscal.py ..................                                  [ 39%]
tests/test_household.py .........................................        [ 47%]
tests/test_output_plots.py ............................................. [ 57%]
                                                                         [ 57%]
tests/test_output_tables.py .............                                [ 60%]
tests/test_parameter_plots.py ...................................        [ 67%]
tests/test_parameter_tables.py .......                                   [ 68%]
tests/test_parameters.py .............                                   [ 71%]
tests/test_run_example.py .F                                             [ 72%]
tests/test_run_ogcore.py .                                               [ 72%]
tests/test_tax.py ..................................                     [ 79%]
tests/test_txfunc.py .........................                           [ 84%]
tests/test_user_inputs.py .........                                      [ 86%]
tests/test_utils.py .................................................... [ 97%]
............                                                             [100%]
```

**ERROR 1**: The `test_SS.py` failure is in the `test_run_SS[Baseline, use zeta]` module. It uses the following input objects and returns `RuntimeError: Steady state equilibrium not found`.
```python
baseline=True
param_updates2 = {
    "use_zeta": True,
    "initial_guess_r_SS": 0.08,
    "initial_guess_TR_SS": 0.06,
}
filename2 = "run_SS_baseline_use_zeta.pkl"
```

**ERROR 2**: The `test_TPI.py` failure is in the `test_run_TPI_extra[Baseline, Kg>0]` module. It uses the following input objects and fails the `assert np.allclose(test_dict[k][: p.T], v[: p.T], rtol=1e-04, atol=1e-04)`.
```python
baseline=True
param_updates8 = {
    "delta_g_annual": 0.02,
    "alpha_I": [0.01],
    "gamma_g": [0.07],
    "initial_Kg_ratio": 0.15,
    "initial_guess_r_SS": 0.06,
    "initial_guess_TR_SS": 0.03,
}
filename8 = os.path.join(
    CUR_PATH, "test_io_data", "run_TPI_outputs_baseline_Kg_nonzero_2.pkl"
)
``` 

**ERROR 3**: The `test_run_example.py` failure is in the `test_run_ogcore_example_output` module. I get the following error.
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
pandas/_libs/parsers.pyx:1952: UnicodeDecodeError
```

**Comment by jdebacker** [comment]
@rickecon Thanks for running the full suite of tests.

My last two commits should fix errors 1 and 2.  

Re error 3: do you have any more info from a traceback? I'm rerunning this test now and no errors initially, but it does take a while to complete.

**Comment by jdebacker** [comment]
Latest PR should fix Error #3, which resulted from a corrupted csv file.

**Comment by rickecon** [comment]
@jdbacker. The `test_SS.py` failure now passes.
```
tests/test_SS.py ...
```

**Comment by rickecon** [comment]
@jdebacker. The `test_TPI.py` failure now passes.
```
tests/test_TPI.py . 
```

**Comment by rickecon** [comment]
Looks great. Thanks @jdebacker.

**Pull request merged**
