### PR TITLE
UBI and `alpha_I` parameter updates

### PR DESCRIPTION
**Pull request by jdebacker**
This PR does the following:

1. Updates the range for the nominal UBI parameters. These were not well defined for using nominal values in different currencies.  Also, negative values may be useful if one wanted to simulate a head tax.
2. Adds a description of the $\alpha_I$ parameter
3. Updates `parameters.py` to extrapolate the `alpha_I` parameter
4. Ensures that `alpha_I` dimensions conform in time path calculations of `I_g`

### CODE REVIEW

**Comment by jdebacker** [comment]
@rickecon This PR is ready to review.

**Comment by rickecon** [comment]
@jdebacker. You will want to update this branch with the main branch as the current version is 0.11.16. So you should update this version to 0.11.17.

**Comment by rickecon** [comment]
@jdebacker. This is ready to merge as soon as you update the versions (and update your branch with the main).

**Comment by jdebacker** [comment]
@rickecon Thanks for noting the more recent version.  I synced to master and bumped the version numbers.  Let me know if this looks good to you.  If so, it's ready to merge.

**Comment by rickecon** [comment]
@jdebacker. There are still some issues with the version number in `CHANGELOG.md`, `setup.py`, and `__init__.py`. Give me a call today if you want to talk through those.

**Comment by jdebacker** [comment]
@rickecon I think I missed committing some changes before.  I've now done that and fixed a couple typos.  Let me know if we need anything else here.

**Comment by rickecon** [comment]
@jdebacker. Looks great. Merging now.

**Pull request merged**
